/**
 * stories.js
 * Contains 10 original English passages for the TypeFlow typing test.
 * Each passage is medium-to-hard difficulty, ~150–250 words,
 * with varied vocabulary, punctuation, numbers, and sentence lengths.
 */

const STORIES = [
  {
    id: 1,
    title: "The Observatory",
    text: `On clear nights, Dr. Eliza Marsh would climb the winding staircase to the observatory's dome and spend hours mapping constellations she'd known since childhood. "There's something humbling about it," she once told her assistant, Marcus. "We look up and see light that left its source thousands of years ago." The telescope — a refurbished 1962 Cassegrain — required careful calibration before each session. She'd tighten the 3 primary adjustment screws, check the declination axis, and peer through the eyepiece until the image sharpened. Marcus admired her patience. Most astronomers relied on automated systems now, but Eliza insisted on manual observation at least twice a week. "Automation captures data," she'd say, "but observation builds intuition." One evening, while tracing the Orion Nebula, she noticed an irregular shimmer in the surrounding field. It wasn't listed in any catalog she knew. Over the next 14 nights, she photographed it repeatedly, comparing exposures and cross-referencing historical plates. The phenomenon persisted. She drafted a careful, methodical report and submitted it to the journal. Whether it would matter — whether anyone would look up and wonder — she couldn't say. But she'd looked. That, she believed, was always worth something.`
  },
  {
    id: 2,
    title: "The Bread Maker",
    text: `Every morning at 4:30, Paulo Ferreira unlocked the bakery's heavy steel door and began what he called "the ritual." He'd measure 800 grams of flour — never estimating, always weighing — and combine it with water at precisely 72°F. The process was meticulous and unforgiving; a deviation of even 5 degrees would alter the crumb's texture by the afternoon. Paulo had learned the craft from his grandmother in Porto, who hadn't owned a thermometer or a scale. She worked entirely by touch and smell, pressing the dough and listening to it breathe. He'd tried to replicate her instinct but eventually accepted that his path was different. Precision was his language. By 6:15, the first loaves entered the oven, and within minutes the street outside began to smell of warm crust and toasted wheat. Neighbors who passed on their way to work often paused at the window. Some knocked, though he wasn't officially open until 7:00. He didn't mind. He'd slip a small warm roll through the door gap — no charge — and return to his bench. "Bread should be shared," he'd say to no one in particular, pressing his thumbs into the next round and watching the indentations slowly rise back, like small hills remembering their shape.`
  },
  {
    id: 3,
    title: "Circuit Breaker",
    text: `The first time Ananya debugged a live production system, she was 26 and three months into her first engineering job. It was a Tuesday at 11:47 p.m. The payment gateway had stopped responding, and 1,200 pending transactions were frozen mid-flight. Her hands were steady — she was proud of that later — but her thoughts were anything but. She opened the terminal, checked the logs, and found a cascade of timeout errors originating from a single microservice. "It's not the database," she typed into the incident channel. "Circuit breaker tripped on the auth validator. I'm resetting it." The response: a string of relieved emoji from engineers who'd been staring at dashboards for 40 minutes. The fix took 8 seconds. The report she'd write afterward took 3 hours. That asymmetry never stopped feeling strange to her. Years later, as a principal engineer, she always told junior developers that the unglamorous part — the thorough post-mortem, the honest accounting of what failed and why — was actually the most valuable part of the whole ordeal. "You don't learn from fixing things quickly," she'd say, leaning against the whiteboard. "You learn from writing down, precisely and without ego, exactly what went wrong." She still had a copy of that first incident report in her personal drive.`
  },
  {
    id: 4,
    title: "The Last Migration",
    text: `Each autumn, the monarch butterflies passed through Cedarville in enormous, slow-moving clouds that turned the sky briefly amber. Residents planned vacations around it. Children were released from school early on the first sighting day. Old Thomas Whitaker, who'd lived on Maple Ridge for 61 years, had never missed a migration. He kept a journal with columns for date, approximate density, wind direction, and temperature. Some years the columns made him uneasy. "Thinner again," he'd write, underlining the word twice. His granddaughter, Priya, would visit during migration season and sit with him on the porch, sharing a thermos of strong tea. She was studying environmental science at a university three states away and carried the weight of her knowledge carefully, not wanting to burden him. He knew anyway. "They're finding it harder to navigate," she said one evening, watching a smaller cluster drift over the eastern ridge. "Temperature gradients have shifted. They're designed for a world that's changing faster than they can adapt." Thomas nodded slowly. He watched the last few stragglers cross the tree line and disappear. Then he opened his journal, wrote the date and density — "sparse, 40% reduction from 2019 average" — and closed it with both hands, pressing the cover flat, as if sealing something important inside.`
  },
  {
    id: 5,
    title: "Deep Salvage",
    text: `At 2,400 meters below the surface, the remotely operated vehicle's lights barely cut through the dark. The footage was grainy, compressed, and delayed by 3 seconds — enough lag to make precise navigation feel like threading a needle wearing oven mitts. Captain Lena Ostroff watched the monitor from the ship's operations deck, one hand resting on the joystick, the other pressing an earpiece against her skull. "Steady," she said to herself, not to anyone listening. The wreck had been on the seabed for 87 years, gradually claimed by barnacles, tubeworms, and rust that spread in slow orange blooms across the hull. Lena's team wasn't there to recover cargo; they were there to document. Historians, marine archaeologists, and a documentary crew had pooled resources to fund a 10-day survey mission. On the second dive, the ROV's camera caught something the sonar hadn't flagged: an intact wooden cabinet, somehow preserved by the near-freezing anoxic conditions, its brass handle still faintly gleaming. Inside — they couldn't open it remotely — something was stacked in neat rows. Lena zoomed in until the image pixelated. Letters, she thought. Or logbooks. She made a note in the dive log: "Cabinet intact at stern, 12 meters from main mast. Recommend recovery attempt, pending preservation assessment." She underlined "intact" and kept watching.`
  },
  {
    id: 6,
    title: "The Cartographer's Dilemma",
    text: `Every map is a lie, Professor Dara once told her undergraduate cartography class. "Not through malice," she clarified, watching their faces, "but through necessity. You cannot represent a sphere on a flat surface without distortion. Every projection you choose is a decision about which truth to sacrifice." The students took notes with varying degrees of enthusiasm. One — a lanky sophomore named Elliot — raised his hand. "So what's the point of making maps at all?" Dara smiled. That was the right question. "A map's value isn't in its perfect accuracy," she said. "It's in its useful approximation. A map that's 70% accurate and fits in your pocket will save your life. A perfect map the size of the territory is useless." She showed them 5 different projections of the same globe: Mercator, Robinson, Winkel tripel, Dymaxion, and Mollweide. Each one made different countries look larger or smaller, more or less central. "Who decided that north should be at the top?" she asked. Nobody answered. "Europeans," she said. "In the 15th century. It's convention, not truth." She let that sit. By the end of the semester, most of the students had quietly stopped thinking of maps as neutral objects. Elliot had started collecting antique ones from estate sales, looking at each for what it chose to leave out.`
  },
  {
    id: 7,
    title: "The Quiet Archive",
    text: `The archive occupied the basement of a building that had once been a municipal courthouse. Its new purpose was quieter, though no less serious. Hannah Reyes had been head archivist for 9 years and had developed the particular stillness that the work required — a patience that was less about waiting and more about sustained attention. She could spend an entire morning on a single box of unsorted documents from the 1880s, sorting letters by date, reading each one carefully before sliding it into an acid-free sleeve. Colleagues from other departments sometimes dropped by and marveled at the silence. "Don't you go mad?" a researcher named Jin asked once, lingering in the doorway. "Quite the opposite," Hannah said, not looking up from a water-damaged ledger she was slowly flattening under glass. "The noise is out there." The archive held records that nobody had looked at in 40, sometimes 70 years. Personal correspondence, property deeds, municipal minutes, handwritten wills. Each document was a small, specific human life condensed into ink on paper. What she found meaningful wasn't the drama — though there was some — but the ordinary: a grocery list tucked inside a court summons, a pressed flower between two letters, a note in the margin reading "remember this." Someone had meant to. She tried to honor that.`
  },
  {
    id: 8,
    title: "Pressure Test",
    text: `The interview started at 9:00 a.m. sharp. Marcus had prepared for 3 weeks: case frameworks, market sizing, mental arithmetic drills, mock sessions with a friend who'd grilled him until he stopped hedging his answers. He sat across from a woman named Claire, who placed a single sheet of paper on the table and slid it toward him without explanation. It showed a graph with no axis labels. "Tell me what you see," she said. He didn't panic — he'd been warned about deliberately ambiguous prompts. He described the shape of the curve: a sharp rise over what appeared to be a short period, then a plateau, then a gradual decline. "It could be adoption lifecycle data," he said. "Or it could be temperature variation, revenue over a product cycle, or a decay curve for some physical process. Without axis labels, I can only describe the structure, not interpret the meaning." Claire nodded. "Good. Most candidates try to force a narrative." She pulled out a second sheet. This one had labels. It was indeed a product adoption curve — but for a category he hadn't expected: water filtration systems in rural clinics across 4 countries. He leaned forward slightly. This, he thought, was interesting. "Walk me through what questions you'd want answered," Claire said. He took a breath and began.`
  },
  {
    id: 9,
    title: "The Repair",
    text: `The violin had been silent for 22 years. It arrived in Sofia Nair's workshop wrapped in an old linen cloth inside a battered case with 2 broken latches and a torn velvet interior. The instrument itself was a late 19th-century German workshop violin — nothing extraordinarily valuable, but clearly once well-played. The varnish was worn through at the shoulder rests, the neck had a slight lateral warp, and one of the bass-bar glue joints had released. There was also a small, precisely cut crack in the upper bout that someone had attempted to repair years ago using what appeared to be carpenter's glue. Sofia set it under her magnifying lamp and worked through a methodical inspection, noting everything in a small cloth-bound book. She had a habit of naming her repairs: not the instruments, but the problems themselves. This one she called "the patient return" — instruments that had been abandoned mid-life, left in closets or attics for decades, then discovered by a descendant and brought in with the instruction: "Please fix it, if you can." She always did what she could. It took her 11 days. When she restrung it and drew a bow across the open G string for the first time, the note that came out was uncertain and thin at first, then gradually warmed, as if remembering something it had nearly forgotten.`
  },
  {
    id: 10,
    title: "Long Division",
    text: `Nina had been teaching 4th grade mathematics for 17 years and had developed a theory about the moment children either embrace or abandon numbers. It wasn't the arithmetic itself that mattered — most kids could memorize times tables with enough repetition — it was the first time they were asked to reason about why something worked rather than just how to execute it. Long division was the great separator. Some children, presented with the algorithm, simply executed it step by step and felt satisfied. Others stared at the partial quotients and remainders and wanted to know what, exactly, they were doing and why. "Those are the ones I love," Nina told a student teacher named Aaron during his observation week. "Not because they're smarter. Because they're unsatisfied." Aaron wrote that down in his notes. Nina moved between desks, stopping to look at each student's work without saying anything immediately. She'd pause, crouch to their level, and ask a question: "What does that remainder mean?" or "Why did you put the 3 there?" One student — a serious girl named Ruth — had invented her own notation for tracking partial steps and was producing correct answers through a method Nina had never seen before. Nina photographed the page with her phone and spent that evening trying to understand it fully. By morning she had. It was, she realized, more elegant than the standard algorithm.`
  }
];
